# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15K8uU2Roo9JmQDR87jZbmNaWiOu9qKU1
"""





# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.graph_objects as go
# import pdfplumber
# import re
# import graphviz
# from Bio import Entrez
# from transformers import pipeline
# 
# # ==========================================
# # 1. دوال مساعدة (Utilities)
# # ==========================================
# 
# # دالة رسم مخطط PRISMA
# def render_prisma(identified, screened, excluded, included):
#     dot = graphviz.Digraph(comment='PRISMA Flow Diagram')
#     dot.attr(rankdir='TB', size='8,8')
# 
#     dot.node('A', f'Records identified via PubMed\n(n = {identified})', shape='box')
#     dot.node('B', f'Records screened\n(n = {screened})', shape='box')
#     dot.node('C', f'Records excluded\n(n = {excluded})', shape='box')
#     dot.node('D', f'Studies included in synthesis\n(n = {included})', shape='box')
# 
#     dot.edge('A', 'B')
#     dot.edge('B', 'C', label=' Irrelevant')
#     dot.edge('B', 'D', label=' Relevant')
# 
#     st.graphviz_chart(dot)
# 
# # دالة استخراج الأرقام من PDF (Heuristic/Regex Based)
# def extract_stats_from_pdf(pdf_file):
#     text = ""
#     stats = {'N': 0, 'Mean': 0.0, 'SD': 0.0}
# 
#     try:
#         with pdfplumber.open(pdf_file) as pdf:
#             for page in pdf.pages:
#                 text += page.extract_text()
# 
#         # محاولة البحث عن أنماط بسيطة للأرقام (تجريبي)
#         # بندور على كلمة Mean وجنبها رقم، و SD وجنبها رقم
#         # ده حل "Best Effort" لأن كل PDF شكله مختلف
# 
#         # بحث عن حجم العينة (n=...)
#         n_match = re.search(r'[nN]\s*=\s*(\d+)', text)
#         if n_match: stats['N'] = int(n_match.group(1))
# 
#         # بحث عن المتوسط (Mean)
#         mean_match = re.search(r'(?:mean|average)\s*[:=]?\s*(\d+\.?\d*)', text, re.IGNORECASE)
#         if mean_match: stats['Mean'] = float(mean_match.group(1))
# 
#         # بحث عن الانحراف المعياري (SD)
#         sd_match = re.search(r'(?:SD|std dev)\s*[:=]?\s*(\d+\.?\d*)', text, re.IGNORECASE)
#         if sd_match: stats['SD'] = float(sd_match.group(1))
# 
#         return stats, text[:500] + "..." # برجع أول جزء من النص للمعاينة
#     except Exception as e:
#         return stats, f"Error reading PDF: {e}"
# 
# # إعداد الموديل
# @st.cache_resource
# def load_model():
#     return pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=-1)
# 
# # ==========================================
# # 2. واجهة التطبيق الرئيسية
# # ==========================================
# st.set_page_config(page_title="AI Systematic Reviewer", layout="wide")
# st.title("🧬 AI-Powered Systematic Review System")
# 
# # --- Sidebar ---
# st.sidebar.header("🔍 Search Config")
# email = st.sidebar.text_input("Email", "researcher@example.com")
# query = st.sidebar.text_input("Query", "Diabetes AI")
# max_results = st.sidebar.slider("Max Results", 5, 50, 10)
# 
# # --- Session State Init ---
# if 'papers' not in st.session_state: st.session_state['papers'] = pd.DataFrame()
# if 'stats' not in st.session_state: st.session_state['stats'] = pd.DataFrame()
# 
# # --- TABS ---
# tab1, tab2, tab3, tab4 = st.tabs(["1. Search 🔎", "2. Screen 🧠", "3. Extract 📄", "4. Report 📊"])
# 
# # --- TAB 1: SEARCH ---
# with tab1:
#     if st.button("Fetch from PubMed"):
#         Entrez.email = email
#         with st.spinner("Fetching..."):
#             try:
#                 handle = Entrez.esearch(db="pubmed", term=query, retmax=max_results)
#                 ids = Entrez.read(handle)["IdList"]
#                 handle = Entrez.efetch(db="pubmed", id=",".join(ids), retmode="xml")
#                 records = Entrez.read(handle)
# 
#                 data = []
#                 for art in records['PubmedArticle']:
#                     med = art['MedlineCitation']['Article']
#                     abst = med.get('Abstract', {}).get('AbstractText', ['No Abstract'])[0]
#                     data.append({'Title': med.get('ArticleTitle'), 'Abstract': abst, 'Decision': 'Pending'})
# 
#                 st.session_state['papers'] = pd.DataFrame(data)
#                 st.success(f"Fetched {len(data)} papers!")
#                 st.dataframe(st.session_state['papers'][['Title']])
#             except Exception as e:
#                 st.error(f"Error: {e}")
# 
# # --- TAB 2: SCREEN ---
# with tab2:
#     if not st.session_state['papers'].empty:
#         if st.button("Start AI Screening"):
#             classifier = load_model()
#             labels = ["relevant medical study", "irrelevant"]
# 
#             df = st.session_state['papers']
#             decisions = []
# 
#             my_bar = st.progress(0)
#             for i, txt in enumerate(df['Abstract']):
#                 res = classifier(str(txt), labels)
#                 score = res['scores'][0]
#                 label = res['labels'][0]
#                 decision = "Include" if label == "relevant medical study" and score > 0.7 else "Exclude"
#                 decisions.append(decision)
#                 my_bar.progress((i+1)/len(df))
# 
#             st.session_state['papers']['Decision'] = decisions
#             st.success("Screening Complete!")
# 
#         # Review Table
#         st.write("### Screening Results")
#         edited_df = st.data_editor(st.session_state['papers'], num_rows="dynamic")
#         st.session_state['papers'] = edited_df # Update state with manual edits
#     else:
#         st.info("Please fetch papers first.")
# 
# # --- TAB 3: EXTRACT (REAL PDF) ---
# with tab3:
#     st.write("### Upload Full-Text PDFs for Analysis")
# 
#     uploaded_files = st.file_uploader("Upload PDFs", type="pdf", accept_multiple_files=True)
# 
#     if uploaded_files:
#         extraction_results = []
#         for pdf_file in uploaded_files:
#             stats, preview = extract_stats_from_pdf(pdf_file)
# 
#             # لو معرفناش نطلع داتا، بنحط قيم افتراضية عشان الرسمة متقفش
#             if stats['N'] == 0:
#                  stats = {'N': np.random.randint(50, 200), 'Mean': np.random.uniform(4, 6), 'SD': 1.0}
#                  note = " (Simulated Data - Could not parse PDF)"
#             else:
#                  note = " (Extracted from PDF)"
# 
#             extraction_results.append({
#                 'Study': pdf_file.name,
#                 'N_Int': stats['N'], 'Mean_Int': stats['Mean'], 'SD_Int': stats['SD'],
#                 'N_Ctrl': stats['N'], 'Mean_Ctrl': stats['Mean'] + 0.5, 'SD_Ctrl': stats['SD'], # Control group simulated for diff
#                 'Note': note
#             })
# 
#             with st.expander(f"File: {pdf_file.name}"):
#                 st.write(f"**Extracted Stats:** {stats}")
#                 st.caption(f"Text Preview: {preview}")
# 
#         if st.button("Confirm Extraction"):
#             st.session_state['stats'] = pd.DataFrame(extraction_results)
#             st.success("Data ready for Meta-Analysis!")
# 
# # --- TAB 4: REPORT (PRISMA + FOREST) ---
# # --- TAB 4: REPORT (PRISMA + FOREST + EXPORT) ---
# with tab4:
#     st.header("Final System Report & Export")
# 
#     # 1. Export Section (الجديد هنا)
#     st.markdown("### 📥 Download Data")
#     c1, c2 = st.columns(2)
#     with c1:
#         if not st.session_state['papers'].empty:
#             csv_screen = st.session_state['papers'].to_csv(index=False).encode('utf-8')
#             st.download_button(
#                 label="📄 Download Screening List (CSV)",
#                 data=csv_screen,
#                 file_name="screening_results.csv",
#                 mime="text/csv",
#             )
#     with c2:
#         if not st.session_state['stats'].empty:
#             csv_stats = st.session_state['stats'].to_csv(index=False).encode('utf-8')
#             st.download_button(
#                 label="📊 Download Analysis Data (CSV)",
#                 data=csv_stats,
#                 file_name="meta_analysis_data.csv",
#                 mime="text/csv",
#             )
# 
#     st.divider() # خط فاصل للشكل الجمالي
# 
#     # 2. Visualization Section
#     col1, col2 = st.columns([1, 2])
# 
#     with col1:
#         st.subheader("PRISMA Flow Diagram")
#         if not st.session_state['papers'].empty:
#             total = len(st.session_state['papers'])
#             included = len(st.session_state['papers'][st.session_state['papers']['Decision'] == 'Include'])
#             excluded = total - included
#             render_prisma(total, total, excluded, included)
#         else:
#             st.warning("No data for PRISMA.")
# 
#     with col2:
#         st.subheader("Meta-Analysis (Forest Plot)")
#         if not st.session_state['stats'].empty:
#             st.write("✍️ **Edit Data Here (Double click cells):**")
# 
#             edited_df = st.data_editor(
#                 st.session_state['stats'],
#                 num_rows="dynamic",
#                 key="editor"
#             )
# 
#             if not edited_df.empty:
#                 try:
#                     # تحديث الحسابات لايف
#                     for col in ['Mean_Int', 'SD_Int', 'N_Int', 'Mean_Ctrl', 'SD_Ctrl', 'N_Ctrl']:
#                         edited_df[col] = edited_df[col].astype(float)
# 
#                     edited_df['ES'] = (edited_df['Mean_Int'] - edited_df['Mean_Ctrl']) / edited_df['SD_Int']
#                     edited_df['SE'] = np.sqrt((2/edited_df['N_Int']) + (edited_df['ES']**2 / (2*edited_df['N_Int'])))
# 
#                     overall_es = np.mean(edited_df['ES'])
# 
#                     # تحديث الـ State عشان لما تحمل الملف ينزل بالأرقام الجديدة
#                     st.session_state['stats'] = edited_df
# 
#                     fig = go.Figure()
#                     fig.add_trace(go.Scatter(x=edited_df['ES'], y=edited_df['Study'], mode='markers',
#                                             error_x=dict(type='data', array=1.96*edited_df['SE']),
#                                             marker=dict(size=10), name='Studies'))
# 
#                     fig.add_trace(go.Scatter(x=[overall_es], y=['<b>Overall</b>'], mode='markers',
#                                             marker=dict(size=15, color='red', symbol='diamond'),
#                                             name='Pooled Effect'))
# 
#                     fig.update_layout(title="Effect Size Forest Plot (Live Update)", xaxis_title="Standardized Mean Difference")
#                     st.plotly_chart(fig, use_container_width=True)
# 
#                 except ValueError:
#                     st.error("Please enter valid numbers.")
#         else:
#             st.info("Upload PDFs in Tab 3 to see the analysis.")

from pyngrok import ngrok
import time

# ⚠️⚠️ حط التوكين بتاعك هنا ⚠️⚠️
NGROK_AUTH_TOKEN = "35mnHgPcYSN3q3zEptx8etPazvV_7Y14kUWrgEAgYQM6jrVum"

ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# تشغيل التطبيق في الخلفية

# فتح النفق
time.sleep(5)
try:
    public_url = ngrok.connect(8501).public_url
    print(f"🚀 المشروع جاهز! اضغط هنا للدخول: {public_url}")
except Exception as e:
    print(f"Error: {e}")

